#!/bin/sh

set -e

file=testurls.txt

if [ "$1" ] ; then
    file="$1"
fi

cat $file | while read url ; do
    case "$url" in
      http*)
        # Save with URL as filename, replacing / with % and dropping trailing slash.
        filename=$(echo "$url" | sed 's%/$%%' |tr / %)
        echo "$url"
        if phantomjs netsniff.js "$url" > "har-data/$filename.har.new" ; then
            mv "har-data/$filename.har.new" "har-data/$filename.har"
        else
            rm "har-data/$filename.har.new"
        fi
        ;;
    esac
done
